<head>
<meta charset="UTF-8">
<title>Bitácora del bitácora</title>
<script type="text/javascript" src="../librerias/javascript/jscalendar/calendar.js"></script>
<link rel="stylesheet" type="text/css" media="all" href="../librerias/javascript/jscalendar/calendar-blue.css" title="win2k-cold-1" />
<link rel="stylesheet" type="text/css" href="css/sys/bitacora.css" />
<style>
    h2{
        text-align:center;
    }
</style>
</head>
<div class="formularios">
	<div class="forma" id="forma1">
            <h2>Timbres</h2>
            <p>Sistema de Timbres para el registro de los timbres que llevan todos los Documentos ingresados al 
            Registro General de la Propiedad</p>
            <p>Version actual:1.0</p>
            <p>Desarrollado por: Carlos Enrique Nuñez Recinos</p>
            <p>Contacto técnico: Carlos Enrique Nuñez Recinos</p>
            <p>Telefono de soporte: 22209040 ext 215</p>
            <p>Correo electrónico: cnunez@rgp.org.gt</p>
	</div>
</div>