<style>
 .img{
        height: 20px;
    } 
</style>
<script type="text/javascript" src="js/reportes.js"></script>
<script type="text/javascript" src="../librerias/javascript/jscalendar/calendar.js"></script>
<link rel="stylesheet" type="text/css" media="all" href="../librerias/javascript/jscalendar/calendar-blue.css" title="win2k-cold-1" />
<script type="text/javascript" src="../librerias/javascript/jscalendar/lang/calendar-es.js"></script>
<script type="text/javascript" src="../librerias/javascript/jscalendar/calendar-setup.js"></script>
<div class="formularios">
    <div class="forma" id="panel">
        <h1>Reporte de los timbres</h1>
            <div class="fields">
                <form action="javascript:void(0);" id="form_reporte">
                    <div class="fields">
                        <table>
                            <tr>
                                <td><label>No. de Documento:</label></td>
                                <td><input id="repo_doc" /></td>
                                <input type="hidden" id="id_repo_doc"/>
                                <td><a id="bus_repo_doc"><img class="img"src="images/icon_search.png"/></a></td>
                            </tr>
                            <tr>
                                <td><label>Colegiado del Notario:</label></td>
                                <td><input id="repo_not" /></td>
                                <input type="hidden" id="id_repo_not"/>
                                <td><a id="bus_repo_not"><img class="img"src="images/icon_search.png"/></a></td>
                            </tr>
                            <tr>
                                <td><label>Valor de los timbres de:</label></td>
                                <td><input id="repo_valor"/></td>
                            </tr>
                            </tr>
                            <tr>
                                <td><label>A valor de los timbres :</label></td>
                                <td><input id="repo_valor_a"/></td>
                            </tr>
                            <tr>
                                <td><label>De fecha de Ingreso:</label></td>
                                <td><input id="repo_fech" /></td>
                                <td><a id="bus_repo_fech"><img class="img" src="images/icon_calendar.png"</a></td>
                            </tr>
                            <tr>
                                <td><label>A fecha de Ingreso:</label></td>
                                <td><input id="repo_fech2" /></td>
                                <td><a id="bus_repo_fech2"><img class="img" src="images/icon_calendar.png"</a></td>
                            </tr>
                            <tr>
                                <td><label>Receptor de timbres:</label></td>
                                <td><input id="repo_egre" /></td>
                                <input type="hidden" id="id_repo_egre"/>
                                <td><a id="bus_repo_egre"><img class="img" src="images/icon_search.png"</a></td>
                            </tr>
                            <tr>
                                <td><label>Estado del Documento</label></td>
                                <td>
                                    <select id="repo_estado">
                                        <option value="">Seleccione uno</option>
                                        <option value="is null">Activo</option>
                                        <option value="is not null">Inactivo</option>
                                    </select>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td><input type="submit" class="buscarLink" id="submit_repo" value="Buscar"</td>
                                <td><input type="reset" class="linkClear" value="Borrar"/></td>
                                <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                &nbsp;&nbsp;&nbsp;&nbsp;</td>
                                <td><a id="submit_exel"><img src="images/icon_xls.png"</a></td>
                                <td>&nbsp;&nbsp;&nbsp;</td>
                                <td><a id="submit_pdf"><img  src="images/pdf.jpg"</a></td>
                            </tr>
                        </table>
                    </div>
                </form>
            </div>
        <div id="div_bus_repo"></div>
    </div>
    <div class="forma"id="div_documento">
        <h1>Busqueda de Documento</h1>
        <form action="javascript:void(0);" id="form_documento">
            <table>
                <tr>
                    <td><label>No. de Documento:</label></td>
                    <td><input id="bus_doc"/></td>
                </tr>
                <tr>
                    <td><label>No. de sticker</label></td>
                    <td><input id="bus_stiker"/></td>
                </tr>
                <tr>
                    <td></td>
                    <td><input type="submit" class="buscarLink" id="bus_documento" value="Buscar"/></td>
                </tr>
            </table>
        </form>
        <div id="div_bus_doc"></div>
        <input type="button" class="backLink" value="Regresar"/>
    </div>
    <div class="forma" id="div_notario">
        <h1>Busqueda de Notario</h1>
        <form action="javascript:void(0);" id="form_notario">
            <table>
                <tr>
                    <td>Colegiado:</td>
                    <td><input id="buscarcolegiado"/></td>
                </tr>
                <tr>
                    <td>Nombre:</td>
                    <td><input id="buscarnombre"/></td>
                </tr>
                <tr>
                    <td>Apellido:</td>
                    <td><input id="buscarapellido"/></td>
                </tr>
                <tr>
                    <td></td>
                    <td><input type="submit" class="buscarLink" id="bus_notario" value="Buscar"</td>
                </tr>
            </table>
        </form>
        <div id="div_bus_not"></div>
        <input type="button" class="backLink" value="Regresar"/>
    </div>
    <div class="forma" id="div_egresor">
        <h1>Buscar Receptor</h1>
        <form action="javascript:void(0);" id="form_receptor">
            <table>
                <tr>
                    <td><label>Nombre:</label></td>
                    <td><input id="recep_name"/></td>
                </tr>
                <tr>
                    <td><label>Apellido:</label></td>
                    <td><input id="recep_ape"/></td>
                </tr>
                <tr>
                    <td><label>DPI:</label></td>
                    <td><input id="recep_dpi"/></td>
                </tr>
                <tr>
                    <td><label>Cedula:</label></td>
                    <td><input id="recep_cedu"/></td>
                </tr>
                <tr>
                    <td></td>
                    <td><input class="buscarLink" value="Buscar" type="submit" id="bus_egresor"/></td>
                </tr>
            </table>
        </form>
        <div id="div_bus_egresor"></div>
        <input type="button" class="backLink" value="Regresar"/>
    </div>
</div>